/**
 * Typed API reference (task T103): every public export of `@opentheme/core` and
 * `@opentheme/core/templates`, with its declaration, generated from the built declarations into
 * `api/core.api.md`. `--check` fails when the committed report differs, so every public API
 * change is reviewed (FR-C102).
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import ts from "typescript";

const pkg = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const entries = { "@opentheme/core": "dist/index.d.ts", "@opentheme/core/templates": "dist/diagnostics/templates.d.ts" };
const out = path.join(pkg, "api/core.api.md");

const program = ts.createProgram(
  Object.values(entries).map((e) => path.join(pkg, e)),
  { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.NodeNext, moduleResolution: ts.ModuleResolutionKind.NodeNext, types: [] },
);
const checker = program.getTypeChecker();
const printer = ts.createPrinter({ removeComments: true, newLine: ts.NewLineKind.LineFeed });

function declarationText(symbol: ts.Symbol): string {
  const target = symbol.flags & ts.SymbolFlags.Alias ? checker.getAliasedSymbol(symbol) : symbol;
  const parts: string[] = [];
  for (const d of target.declarations ?? []) {
    let node: ts.Node = d;
    if (ts.isVariableDeclaration(d)) node = d.parent.parent;
    parts.push(printer.printNode(ts.EmitHint.Unspecified, node, d.getSourceFile()).trim());
  }
  return parts.join("\n");
}

let md = "# `@opentheme/core` API report\n\nGenerated by `scripts/api-report.ts` from the built declarations. Do not edit.\n";
for (const [name, file] of Object.entries(entries)) {
  const source = program.getSourceFile(path.join(pkg, file));
  if (!source) throw new Error(`missing ${file}; run the build first`);
  const moduleSymbol = checker.getSymbolAtLocation(source)!;
  const exports = checker.getExportsOfModule(moduleSymbol).sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
  md += `\n## \`${name}\`\n`;
  for (const s of exports) md += `\n### \`${s.name}\`\n\n\`\`\`ts\n${declarationText(s)}\n\`\`\`\n`;
}

if (process.argv.includes("--check")) {
  let committed = "";
  try {
    committed = readFileSync(out, "utf8");
  } catch {
    // missing report
  }
  if (committed !== md) {
    process.stderr.write("api:core: the public API changed; review it and run `pnpm --filter @opentheme/core run api` to update api/core.api.md\n");
    process.exit(1);
  }
  process.stdout.write("api:core: ok\n");
} else {
  mkdirSync(path.dirname(out), { recursive: true });
  writeFileSync(out, md);
  process.stdout.write(`api:core: wrote ${path.relative(pkg, out)}\n`);
}
