/**
 * Build-time generation of Core's embedded normative artifacts (research CR4, CR6).
 * Output: packages/core/src/generated/ — never edited by hand; freshness is checked by spec-lint.
 *
 * - registries.ts: the registries Core needs, with documentation-only keys removed
 * - templates.ts: English diagnostic message and hint templates (optional module)
 * - baseline.ts: the specification baseline theme
 * - validators.ts: Ajv standalone validators, bundled with esbuild so Core has no runtime
 *   dependency and generates no code at runtime
 */
import { createHash } from "node:crypto";
import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import Ajv2020Module from "ajv/dist/2020.js";
import standaloneModule from "ajv/dist/standalone/index.js";
import { build } from "esbuild";

const here = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(here, "../../..");
const outDir = path.join(here, "../src/generated");
const HEADER = "/* Generated by packages/core/scripts/generate-artifacts.ts — do not edit. */\n";

type Json = null | boolean | number | string | Json[] | { [k: string]: Json };

/** Documentation-only members: examples always; titles, descriptions, comments when text. */
const EXAMPLE_KEYS = new Set(["example", "examples"]);
const TEXT_DOC_KEYS = new Set(["description", "title", "$comment"]);

function stripDocs(value: Json, keepDescriptions: boolean): Json {
  if (Array.isArray(value)) return value.map((v) => stripDocs(v, keepDescriptions));
  if (value && typeof value === "object") {
    const out: { [k: string]: Json } = {};
    for (const [k, v] of Object.entries(value)) {
      if (EXAMPLE_KEYS.has(k)) continue;
      // A key such as a part named "title" holds data (an object), not documentation text.
      if (TEXT_DOC_KEYS.has(k) && typeof v === "string" && !(keepDescriptions && k === "description")) continue;
      out[k] = stripDocs(v, keepDescriptions);
    }
    return out;
  }
  return value;
}

async function readJson(rel: string): Promise<Json> {
  return JSON.parse(await readFile(path.join(repoRoot, rel), "utf8")) as Json;
}

async function collectSchemas(dir: string): Promise<string[]> {
  const out: string[] = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...(await collectSchemas(full)));
    else if (entry.name.endsWith(".schema.json")) out.push(full);
  }
  return out.sort();
}

function literal(value: Json): string {
  return JSON.stringify(value, null, 1);
}

async function generateRegistries(): Promise<void> {
  const names = [
    "semantic-baseline",
    "component-catalog",
    "context-dimensions",
    "customization-points",
    "transformations",
    "forced-colors",
    "limits",
  ] as const;
  const lines: string[] = [HEADER];
  for (const name of names) {
    const data = await readJson(`specification/registry/1.0/${name}.json`);
    const stripped = stripDocs(data, name === "customization-points");
    const ident = name.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());
    lines.push(`export const ${ident}: unknown = ${literal(stripped)};\n`);
  }
  const diagnostics = (await readJson("specification/registry/1.0/diagnostics.json")) as {
    codes: Array<{ code: string; severity: string; rules: string[]; message: string; hint: string }>;
  };
  const codes: Record<string, { severity: string; rule: string; message: string; hint: string }> = {};
  for (const c of diagnostics.codes) {
    codes[c.code] = { severity: c.severity, rule: c.rules[0] ?? "", message: c.message, hint: c.hint };
  }
  lines.push(
    `export const diagnosticCodes: Readonly<Record<string, { readonly severity: "error" | "warning" | "info"; readonly rule: string; readonly message: string; readonly hint: string }>> = ${literal(codes as unknown as Json)};\n`,
  );
  await writeFile(path.join(outDir, "registries.ts"), lines.join("\n"), "utf8");

  const templates: Record<string, { message: string; hint: string }> = {};
  const full = (await readJson("specification/registry/1.0/diagnostics.json")) as {
    codes: Array<{ code: string; messageTemplate: string; hintTemplate: string }>;
  };
  for (const c of full.codes) templates[c.code] = { message: c.messageTemplate, hint: c.hintTemplate };
  await writeFile(
    path.join(outDir, "templates.ts"),
    `${HEADER}export const englishTemplates: Readonly<Record<string, { readonly message: string; readonly hint: string }>> = ${literal(templates as unknown as Json)};\n`,
    "utf8",
  );
}

async function generateBaseline(): Promise<void> {
  const doc = await readJson("specification/themes/baseline/org.opentheme.baseline.opentheme.json");
  await writeFile(
    path.join(outDir, "baseline.ts"),
    `${HEADER}export const baselineTheme: unknown = ${literal(doc)};\n`,
    "utf8",
  );
}

async function generateValidators(): Promise<void> {
  const Ajv2020 = (Ajv2020Module as unknown as { default: typeof Ajv2020Module }).default ?? Ajv2020Module;
  const standaloneCode =
    (standaloneModule as unknown as { default: typeof standaloneModule }).default ?? standaloneModule;
  // biome-ignore lint/suspicious/noExplicitAny: Ajv constructor typing differs across module formats
  const ajv = new (Ajv2020 as any)({
    allErrors: true,
    strict: false,
    verbose: true,
    code: { source: true, esm: true, lines: false },
  });
  for (const file of await collectSchemas(path.join(repoRoot, "specification/schemas"))) {
    const schema = JSON.parse(await readFile(file, "utf8")) as { $id?: string };
    if (schema.$id) ajv.addSchema(schema);
  }
  const source = standaloneCode(ajv, {
    validateThemeSchema: "https://opentheme.org/schemas/1.0/theme.schema.json",
    validateHostSchema: "https://opentheme.org/schemas/1.0/host-declaration.schema.json",
    validatePreferencesSchema:
      "https://opentheme.org/schemas/user-preferences/1.0/user-preferences.schema.json",
  });
  const tmp = path.join(outDir, ".validators.raw.mjs");
  await writeFile(tmp, source, "utf8");
  const bundled = await build({
    entryPoints: [tmp],
    bundle: true,
    format: "esm",
    platform: "neutral",
    target: "es2022",
    write: false,
    legalComments: "none",
    absWorkingDir: path.join(here, ".."),
  });
  await rm(tmp);
  const code = bundled.outputFiles[0]!.text;
  if (/\bnew Function\b|\beval\(/.test(code)) {
    throw new Error("generated validators must not use eval or new Function");
  }
  await writeFile(
    path.join(outDir, "validators.ts"),
    `${HEADER}// @ts-nocheck — bundled Ajv standalone output; typed through validators-types.ts\n${code}`,
    "utf8",
  );
}

/** Every input whose content determines the generated output (checked by spec-lint). */
export async function artifactInputs(): Promise<string[]> {
  const schemas = await collectSchemas(path.join(repoRoot, "specification/schemas"));
  return [
    "packages/core/scripts/generate-artifacts.ts",
    "specification/themes/baseline/org.opentheme.baseline.opentheme.json",
    ...[
      "semantic-baseline",
      "component-catalog",
      "context-dimensions",
      "customization-points",
      "transformations",
      "forced-colors",
      "limits",
      "diagnostics",
    ].map((n) => `specification/registry/1.0/${n}.json`),
    ...schemas.map((f) => path.relative(repoRoot, f).replace(/\\/g, "/")),
  ];
}

async function writeStamp(): Promise<void> {
  const inputs: Record<string, string> = {};
  for (const rel of await artifactInputs()) {
    const bytes = await readFile(path.join(repoRoot, rel));
    inputs[rel] = createHash("sha256").update(bytes).digest("hex");
  }
  await writeFile(path.join(outDir, ".stamp.json"), `${JSON.stringify({ inputs }, null, 2)}\n`, "utf8");
}

/**
 * The JSON Schemas Core consumes, shipped unchanged in the package under `schemas/` (NFR-C006):
 * every schema under specification/schemas, with its relative path kept so `$ref`s still resolve.
 */
async function copySchemas(): Promise<void> {
  const from = path.join(repoRoot, "specification/schemas");
  const to = path.join(here, "../schemas");
  await rm(to, { recursive: true, force: true });
  const walk = async (dir: string): Promise<void> => {
    for (const entry of await readdir(dir, { withFileTypes: true })) {
      const src = path.join(dir, entry.name);
      if (entry.isDirectory()) await walk(src);
      else if (entry.name.endsWith(".json")) {
        const dst = path.join(to, path.relative(from, src));
        await mkdir(path.dirname(dst), { recursive: true });
        await writeFile(dst, await readFile(src));
      }
    }
  };
  await walk(from);
}

async function main(): Promise<void> {
  await mkdir(outDir, { recursive: true });
  await copySchemas();
  await generateRegistries();
  await generateBaseline();
  await generateValidators();
  await writeStamp();
  process.stdout.write("core: generated registries, templates, baseline, validators; copied schemas\n");
}

main().catch((err: unknown) => {
  process.stderr.write(`${err instanceof Error ? err.stack : String(err)}\n`);
  process.exit(1);
});
