/**
 * Generate TypeScript types from every schema under specification/schemas/ (all versions).
 * Wired into `pnpm build` via @opentheme/types; freshness checked by spec-lint (T030).
 */
import { mkdir, readdir, readFile, writeFile, stat } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";

const here = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(here, "../../..");
const schemasRoot = path.join(repoRoot, "specification/schemas");
const outDir = path.join(here, "../src/generated");
/** Second output: public types shipped by @opentheme/core (research CR17, FR-C104). */
const coreOutDir = path.join(repoRoot, "packages/core/src/generated/types");
const CORE_TYPES = new Set([
  "specification/schemas/1.0/resolved-theme.schema.json",
  "specification/schemas/1.0/resolution-input.schema.json",
  "specification/schemas/1.0/diagnostic.schema.json",
  "specification/schemas/user-preferences/1.0/user-preferences.schema.json",
]);

/** json-schema-to-typescript names the root type from `title`; find that exported name. */
function rootTypeName(ts: string, schema: Record<string, unknown>, fallback: string): string | null {
  const title = typeof schema.title === "string" ? schema.title : fallback;
  const pascal = title
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
  return new RegExp(`^export (interface|type) ${pascal}\\b`, "m").test(ts) ? pascal : null;
}

async function collectSchemas(dir: string): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true });
  const files: string[] = [];
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await collectSchemas(full)));
    } else if (entry.name.endsWith(".schema.json")) {
      files.push(full);
    }
  }
  return files.sort();
}

function toTypeName(filePath: string): string {
  const base = path.basename(filePath, ".schema.json");
  return base
    .split(/[-_/]/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

/**
 * `oneOf`/`anyOf` whose branches only add string patterns do not change the TypeScript type, but
 * json-schema-to-typescript renders them as an object type; drop them so `type: "string"` stays.
 */
function withoutPatternCombinators(v: unknown): unknown {
  if (Array.isArray(v)) return v.map(withoutPatternCombinators);
  if (!v || typeof v !== "object") return v;
  const out: Record<string, unknown> = {};
  for (const [k, x] of Object.entries(v as Record<string, unknown>)) {
    const patternOnly =
      (k === "oneOf" || k === "anyOf") &&
      Array.isArray(x) &&
      x.every((b) => b && typeof b === "object" && Object.keys(b).every((bk) => bk === "pattern" || bk === "description"));
    if (!patternOnly) out[k] = withoutPatternCombinators(x);
  }
  return out;
}

async function main(): Promise<void> {
  await mkdir(outDir, { recursive: true });
  await mkdir(coreOutDir, { recursive: true });
  const schemas = await collectSchemas(schemasRoot);
  const indexLines: string[] = [
    "/* Generated by tools/types/scripts/generate.ts — do not edit by hand. */",
    "",
  ];
  const coreIndexLines: string[] = [...indexLines];

  for (const schemaPath of schemas) {
    const raw = await readFile(schemaPath, "utf8");
    const schema = withoutPatternCombinators(JSON.parse(raw)) as Record<string, unknown>;
    const name = toTypeName(schemaPath);
    const rel = path.relative(repoRoot, schemaPath).replace(/\\/g, "/");
    try {
      const ts = await compile(schema, name, {
        bannerComment: `/* Generated from ${rel} */`,
        cwd: path.dirname(schemaPath),
        unreachableDefinitions: true,
        unknownAny: false,
      });
      const outFile = path.join(outDir, `${name}.ts`);
      await writeFile(outFile, ts, "utf8");
      const root = rootTypeName(ts, schema, name);
      const line = root
        ? `export type { ${root} as ${name} } from "./${name}.js";`
        : `// ${name}: no root type emitted for ${rel}`;
      indexLines.push(line);
      if (CORE_TYPES.has(rel)) {
        await writeFile(path.join(coreOutDir, `${name}.ts`), ts, "utf8");
        coreIndexLines.push(line);
      }
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      process.stderr.write(`types:generate skipped ${rel}: ${message}\n`);
      const stub = `/* Generated stub for ${rel} (compile deferred) */\nexport type ${name} = Record<string, unknown>;\n`;
      await writeFile(path.join(outDir, `${name}.ts`), stub, "utf8");
      indexLines.push(`export type { ${name} } from "./${name}.js";`);
    }
  }

  indexLines.push("");
  await writeFile(path.join(outDir, "index.ts"), indexLines.join("\n"), "utf8");
  coreIndexLines.push("");
  await writeFile(path.join(coreOutDir, "index.ts"), coreIndexLines.join("\n"), "utf8");

  const stamp = {
    generatedAt: new Date().toISOString(),
    schemaCount: schemas.length,
    schemas: await Promise.all(
      schemas.map(async (p) => ({
        path: path.relative(repoRoot, p).replace(/\\/g, "/"),
        mtimeMs: (await stat(p)).mtimeMs,
      })),
    ),
  };
  await writeFile(
    path.join(outDir, ".stamp.json"),
    `${JSON.stringify(stamp, null, 2)}\n`,
    "utf8",
  );
  process.stdout.write(`types: generated ${schemas.length} schema type files\n`);
}

main().catch((error: unknown) => {
  process.stderr.write(`${error instanceof Error ? error.stack : String(error)}\n`);
  process.exit(1);
});
