/**
 * Embeds the data the interchange needs (T002): each semantic baseline path's type (export `$type`,
 * import role checks) and the seed-only example's seeds (import default). Checked by a test.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "../../..");
const json = (rel: string) => JSON.parse(readFileSync(path.join(root, rel), "utf8")) as Record<string, unknown>;

export function generatedSource(): string {
  const baseline = json("specification/registry/1.0/semantic-baseline.json") as { tokens: { path: string; type: string }[] };
  const example = json("specification/examples/01-minimal-seed-only.opentheme.json") as { seeds: unknown };
  const types = Object.fromEntries(baseline.tokens.map((t) => [t.path, t.type]));
  return [
    "// Generated by packages/dtcg/scripts/generate.ts from specification/registry/1.0/semantic-baseline.json",
    "// and specification/examples/01-minimal-seed-only.opentheme.json. Do not edit.",
    `export const BASELINE_TYPES: Readonly<Record<string, string>> = ${JSON.stringify(types)};`,
    `export const DEFAULT_SEEDS: Readonly<Record<string, unknown>> = ${JSON.stringify(example.seeds)};`,
    "",
  ].join("\n");
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  mkdirSync(path.join(here, "../src/generated"), { recursive: true });
  writeFileSync(path.join(here, "../src/generated/data.ts"), generatedSource());
}
