/**
 * Embeds the seed-only minimal example (the starting point of `opentheme init`) and the
 * specification version into src/generated/minimal-theme.ts (T004). Checked by a freshness test.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "../../..");

export function generatedSource(): string {
  const example = JSON.parse(
    readFileSync(path.join(root, "specification/examples/01-minimal-seed-only.opentheme.json"), "utf8"),
  ) as Record<string, unknown>;
  const version = (JSON.parse(readFileSync(path.join(root, "specification/registry/1.0/limits.json"), "utf8")) as { version: string })
    .version;
  return [
    "// Generated by packages/cli/scripts/generate.ts from specification/examples/01-minimal-seed-only.opentheme.json",
    "// and specification/registry/1.0/limits.json. Do not edit.",
    `export const SPEC_VERSION = ${JSON.stringify(version)};`,
    `export const MINIMAL_THEME: Readonly<Record<string, unknown>> = ${JSON.stringify(example)};`,
    "",
  ].join("\n");
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  mkdirSync(path.join(here, "../src/generated"), { recursive: true });
  writeFileSync(path.join(here, "../src/generated/minimal-theme.ts"), generatedSource());
}
