/**
 * Embeds the registry data the serializer needs (T009): the CSS system color for each forced-colors
 * role, and the closed list of generic font families. The output is committed and checked by a test.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "../../..");

export function generatedSource(): string {
  const forced = JSON.parse(readFileSync(path.join(root, "specification/registry/1.0/forced-colors.json"), "utf8")) as {
    roles: { id: string; cssSystemColorHint: string }[];
  };
  const tokens = JSON.parse(readFileSync(path.join(root, "specification/schemas/1.0/defs/tokens.schema.json"), "utf8")) as {
    $defs: { genericFamily: { enum: string[] } };
  };
  const colors = Object.fromEntries(forced.roles.map((r) => [r.id, r.cssSystemColorHint]));
  return [
    "// Generated by packages/web/scripts/generate.ts from specification/registry/1.0/forced-colors.json",
    "// and specification/schemas/1.0/defs/tokens.schema.json. Do not edit.",
    `export const SYSTEM_COLORS: Readonly<Record<string, string>> = Object.freeze(${JSON.stringify(colors)});`,
    `export const GENERIC_FAMILIES: ReadonlySet<string> = new Set(${JSON.stringify(tokens.$defs.genericFamily.enum)});`,
    "",
  ].join("\n");
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  mkdirSync(path.join(here, "../src/generated"), { recursive: true });
  writeFileSync(path.join(here, "../src/generated/registry.ts"), generatedSource());
}
